Echarts implementation
apotdevin/thunderhub pull request #536
Opened 2023-06-06 00:56 UTC by AmbossKeegan

Selected the Transaction graph as the candidate for the move to echarts. 
- Created BarChartV2 as the BarChart component
- eCharts required next-transpile-modules in order to work

<img width="1022" alt="Screen Shot 2023-06-05 at 8 09 11 PM" src="https://github.com/apotdevin/thunderhub/assets/132274422/4a01a05e-9f48-4f5a-938c-429a76260d0d">

2023-06-06 13:52 UTC, AmbossKeegan commented on src/client/src/components/chart/BarChartV2.tsx
> +        data: data.map((d: any) => d.Invoices),
We will need to abstract this part out to the parent such that data of various kinds can be passed to the BarChart component.

2023-06-07 21:18 UTC, secondl1ght reviewed
Ok nice work, after my review I have a few suggestions/questions:

- we should probably change the minimum Y Axis interval to 1 because you can't have a fraction of a payment or invoice
- the time scale displayed on the X Axis is different from the original chart, not sure if this matters?
- it looks to me like the Payments chart is not working (I made a payment but nothing was displayed when I toggled the chart however it's working on master)
- there is an error in the console about server rendering (this is also on master but might be an opportunity to fix it now)
- the tooltip styling is different from the original chart (the original is much more minimal which I like better but it is personal preference)
- rather than trying to create a component for this Bar Chart we could just place the code inline in the desired file (like we talked about on the call today this approach is more flexible)
- the legend and main titles don't match the dropdown values for example Amount/Tokens vs. Count/Amount
- the previous chart did not have a Title or Legend, do we want to keep the new chart also minimal in appearance?

Please let me know if any of my comments are not clear, I can provide screenshots or more details if needed.

2023-06-12 20:32 UTC, secondl1ght reviewed
My comments are mostly nits at this point so I think it's ready for @apotdevin to take a final review now and see if he is happy with it.

- do we need a y label if its the same as the title?
- make title copy match dropdown copy for consistency
- ~is there a date format standard on TH like there is for Amboss? (for example to use in the tooltip dates)~
- we could format the volume numbers in the tooltip to make them more readable by adding commas (we could port the function over from Amboss)
- I like the colors/style of the original tooltip but again this is just a personal preference or nit

2023-06-13 08:50 UTC, apotdevin reviewed
Let's also reduce the padding the chart has - seems to big right now

2023-06-13 08:50 UTC, apotdevin commented on src/client/next.config.js
> +  transpilePackages: ['echarts', 'echarts-for-react', 'zrender'],
Hadn't seen this config before. Why is it needed?

2023-06-13 08:50 UTC, apotdevin commented on src/client/src/components/generic/helpers.tsx
> +  return format(new Date(date), style || 'dd/MM/yyyy - HH:mm:ss');
Let's use this example date for the default: `2022.02.24 8:32:21`

2023-06-13 08:50 UTC, apotdevin commented on src/client/src/views/home/reports/flow/TransactionGraph.tsx
> +          title: `# of ${showPay ? 'Payments' : 'Invoices'}`,
```suggestion
          yAxisLabel: `Amount of ${showPay ? 'Payments' : 'Invoices'}`,
          title: `Amount of ${showPay ? 'Payments' : 'Invoices'}`,
```

2023-06-13 08:50 UTC, apotdevin commented on src/client/src/views/home/reports/flow/TransactionGraph.tsx
> +  ) {
Nice!

2023-06-13 13:58 UTC, AmbossKeegan commented on src/client/next.config.js
> +  transpilePackages: ['echarts', 'echarts-for-react', 'zrender'],
https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages

Speculation: It has something to do with the monorepo and an inability to pull and render components from those packages without transpiling in NextJS.

2023-07-04 01:55 UTC, secondl1ght requested changes
Nice, left some comments/suggestions inline!

2023-07-05 21:39 UTC, apotdevin commented
- Padding around this chart is weird, lets try to center all charts inside the card.
<img width="1033" alt="image" src="https://github.com/apotdevin/thunderhub/assets/31413433/283f24ea-3b88-41a3-b27f-b16e787cd880">

- Same here. Can we center and add the x-axis. There also seems to be an extra empty category? 
<img width="1033" alt="image" src="https://github.com/apotdevin/thunderhub/assets/31413433/c8a12dae-40de-4256-a699-1b21859a898e">

- For the y-axis can we format numbers similar to amboss space? `1800000` -> `1.8m`
<img width="109" alt="image" src="https://github.com/apotdevin/thunderhub/assets/31413433/3463e6c4-6895-4692-9d6e-dc47abbdab09">

- This chart get's cut off 
<img width="964" alt="image" src="https://github.com/apotdevin/thunderhub/assets/31413433/7c3bea49-8434-461e-97ca-e7c09c0dad3f">

2023-07-24 08:03 UTC, apotdevin commented
What is needed to finish this PR @AmbossKeegan ?

2023-07-30 23:33 UTC, AmbossKeegan commented
> What is needed to finish this PR @AmbossKeegan ?

Just pushed a commit with code that bounds the sankey data inside its chart. Also provided a mock-data function that can be used to generate an arbitrarily large sankey dataset for testing purposes.

As far as I am aware, this was the last outstanding piece of feedback that needed to be addressed for this PR.

2023-08-18 16:15 UTC, merged