fix: new react table
apotdevin/thunderhub pull request #538
Opened 2023-06-07 19:33 UTC by AmbossKeegan

Move to tanstack react-table

<img width="1213" alt="Screen Shot 2023-06-07 at 4 32 20 PM" src="https://github.com/apotdevin/thunderhub/assets/132274422/056a1aad-eecf-4b2d-8edb-2cf69fa93e73">

2023-06-08 19:00 UTC, secondl1ght requested changes
Ok here are my comments:

- there is no sorting functionality in the new table but there is on the original table
- the table column titles wrap in this new version (we should not allow them to do this)
- I left some more comments inline in the code

2023-06-12 19:51 UTC, secondl1ght reviewed
Nice, thanks for making the updates!

2023-06-13 10:33 UTC, apotdevin commented
@secondl1ght is it good to be implemented with the rest of the tables? If so let's do this so that we can remove the old dependency

2023-06-13 15:49 UTC, secondl1ght commented
> @secondl1ght is it good to be implemented with the rest of the tables? If so let's do this so that we can remove the old dependency

Yes I think @AmbossKeegan just did one table and one chart in the echarts PR #536 as a proof of concept, but he plans on porting the remaining charts/tables over once these initial updates were approved.

2023-06-13 15:51 UTC, AmbossKeegan commented
Thats correct. We want to perfect one table so the base format is set and I can go and modify the rest of the tables more or less unencumbered. I can do it all in this PR if we want, or merge this in and start a new branch for the rest of them.

2023-06-13 16:15 UTC, merged