React tables migration
apotdevin/thunderhub pull request #540
Opened 2023-06-14 23:57 UTC by AmbossKeegan

- finished code-wide migration to Tanstack react-tables
- deleted old dependency & files
- updated package.json / package-lock.json

2023-06-26 19:22 UTC, secondl1ght requested changes
Nice work, left some comments inline!

2023-06-26 19:22 UTC, secondl1ght commented on src/client/src/components/table/ColumnConfigurations.tsx
> +import { Table } from '@tanstack/react-table';
Was the main change here just moving this into it's own component file or did the functionality need to be changed with the new package? (didn't do a full review on this file)

2023-06-26 19:22 UTC, secondl1ght commented on src/client/src/components/table/DebouncedInput.tsx
> +import { useState, useEffect } from 'react';
Was the main change here just moving this into it's own component file or did the functionality need to be changed with the new package? (didn't do a full review on this file)

2023-06-26 19:22 UTC, secondl1ght commented on src/client/src/components/table/index.tsx
> +      ,
Syntax error here - not needed `,` character.

2023-06-27 15:44 UTC, AmbossKeegan commented on src/client/src/views/home/reports/mempool/index.tsx
> +        <Table alignCenter={true} columns={columns} data={data} />
This table only ever has a single row in it. Its the low, medium, high fee table, so this one doesn't need sorting.

2023-06-27 15:48 UTC, AmbossKeegan commented on src/client/src/components/table/DebouncedInput.tsx
> +import { useState, useEffect } from 'react';
The main change was to put this in its own file to reduce file size in the file it was declared in, as well as being able to use this component elsewhere.

2023-06-27 15:48 UTC, AmbossKeegan commented on src/client/src/components/table/ColumnConfigurations.tsx
> +import { Table } from '@tanstack/react-table';
The main change was to put this in its own file to reduce file size in the file it was declared in, as well as being able to use this component elsewhere.

2023-06-27 15:50 UTC, AmbossKeegan commented on src/client/src/views/chain/utxos/ChainUtxos.tsx
> +            enableSorting: false,
I made some discretionary changes as to which columns ought to be sortable and not. To me, the addresses as well as their formats are not within the realm of things that people would sort by. I'm happy to revert and make all columns that we're sortable previously sortable again. However, I believe in the previous implementation everything was sortable by default, whereas now I am exercising a little more critical thinking around which columns makes sense to be able to sort.

2023-06-28 20:24 UTC, secondl1ght approved these changes

2023-07-14 02:57 UTC, SazKeegan commented on src/client/src/views/dashboard/widgets/external/mempool.tsx
> +    { header: 'Fastest', accessorKey: 'fast' },
The mempool table looks alright on mobile. Desktop and mobile there is no wrap.

2023-07-14 03:00 UTC, AmbossKeegan commented on src/client/src/views/dashboard/widgets/external/mempool.tsx
> +    { header: 'Fastest', accessorKey: 'fast' },
The Mempool table looks alright on mobile and desktop. There is no wrap on either.

2023-07-14 03:00 UTC, AmbossKeegan commented on src/client/src/views/dashboard/widgets/external/mempool.tsx
> +    { header: 'Hour', accessorKey: 'hour' },
The Mempool table looks alright on mobile and desktop. There is no wrap on either.

2023-07-14 03:03 UTC, merged